CREATE TABLE IF NOT EXISTS AGREEMENT
(
  id INT PRIMARY KEY AUTO_INCREMENT,
  title VARCHAR(255) NOT NULL ,
  description VARCHAR(255) NOT NULL,
  date_compliance DATE NOT NULL,
  observation VARCHAR(255),
  state VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS  RESPONSIBLE
(
  id INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255),
  lastname VARCHAR(255),
  ocupation VARCHAR(255),
  email VARCHAR(255),
  agreementid INT NOT NULL ,
  CONSTRAINT BLA FOREIGN KEY (agreementid) REFERENCES AGREEMENT (ID)
);

CREATE TABLE IF NOT EXISTS USER
(
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(255) UNIQUE ,
  password VARCHAR(255) NOT NULL ,
  email VARCHAR(255) NOT NULL ,
  rol VARCHAR(255) NOT NULL
);